import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {validateSubmission} from '../shared/validation.ts';
import {score} from '../shared/scoring.ts';
import {pillars} from '../shared/questions.ts';

test('migração, gravação atômica, RLS, filtros, métricas e duplicação',async()=>{
 const db=new PGlite();
 await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,service_role;grant execute on function auth.uid() to authenticated,service_role;");
 const file=(await readdir('supabase/migrations')).find(x=>x.endsWith('_initial_diagnostic.sql'))!;
 await db.exec(await readFile('supabase/migrations/'+file,'utf8'));
 const admin='00000000-0000-0000-0000-000000000001',user='00000000-0000-0000-0000-000000000002';
 await db.exec("insert into auth.users values ('"+admin+"'),('"+user+"');insert into public.admin_users(user_id) values('"+admin+"');");
 const input={token:'a'.repeat(64),answers:Object.fromEntries(Array.from({length:18},(_,i)=>[String(i+1),![0,1,9,10,17].includes(i)])),comments:Object.fromEntries(pillars.map(p=>[p.id,'Comentário de teste.'])),contact:{name:'Teste automatizado',email:'teste@example.invalid',whatsapp:'',role:'Pastor titular',city:'Cidade de teste',state:'SP',church_size:'Até 50 pessoas',privacy_consent:true,marketing_consent:true,whatsapp_consent:false},attribution:{utm_source:'teste'},challenge_90_days:'Desafio de teste.'};
 const {token,...payload}=validateSubmission(input);
 await db.exec("set role service_role;insert into public.quiz_sessions(token_hash,started_at) values('hash-1',now()-interval '1 minute'),('hash-2',now()-interval '2 minutes'),('hash-3',now()-interval '3 minutes');");
 const execute=async(hash:string,p:any)=>(await db.query<{result:any}>('select public.complete_diagnostic($1,$2::jsonb,$3) as result',[hash,JSON.stringify(p),'https://example.org/privacy'])).rows[0].result;
 const result=await execute('hash-1',payload);assert.deepEqual(result,score(input.answers));
 assert.deepEqual(result.priority_pillars,['vision','discipleship']);assert.deepEqual(result.secondary_pillars,['conflict']);
 assert.equal((await db.query<any>('select count(*)::int as n from public.answers')).rows[0].n,18);
 assert.equal((await db.query<any>('select count(*)::int as n from public.answers where comment is not null')).rows[0].n,6);
 const repeat=await execute('hash-1',{...payload,answers:Object.fromEntries(Array.from({length:18},(_,i)=>[i+1,true]))});assert.deepEqual(repeat,result);
 assert.equal((await db.query<any>('select count(*)::int as n from public.leads')).rows[0].n,1);
 assert.equal((await db.query<any>('select count(*)::int as n from public.marketing_outbox')).rows[0].n,1);
 await assert.rejects(()=>execute('hash-2',{...payload,contact:{...payload.contact,privacy_consent:false}}));
 assert.equal((await db.query<any>('select count(*)::int as n from public.leads')).rows[0].n,1);
 assert.equal((await db.query<any>('select count(*)::int as n from public.submissions')).rows[0].n,1);
 const bad={...payload,answers:{...payload.answers,1:'false'}};await assert.rejects(()=>execute('hash-2',bad));
 const allYes={...payload,contact:{...payload.contact,marketing_consent:false},answers:Object.fromEntries(Array.from({length:18},(_,i)=>[i+1,true]))};
 assert.deepEqual((await execute('hash-2',allYes)).priority_pillars,[]);
 assert.equal((await db.query<any>('select count(*)::int as n from public.marketing_outbox')).rows[0].n,1);
 for(let i=0;i<3;i++)assert.equal((await db.query<any>("select public.consume_rate_limit('bucket',2,3600) as allowed")).rows[0].allowed,i<2);
 await db.exec('reset role;set role anon;');
 for(const table of ['leads','submissions','answers','admin_records','quiz_sessions'])await assert.rejects(()=>db.query('select * from public.'+table));
 await assert.rejects(()=>execute('hash-1',payload));
 await db.exec("reset role;set role authenticated;set request.jwt.claim.sub='"+user+"';");
 assert.equal((await db.query('select * from public.leads')).rows.length,0);
 assert.equal((await db.query('select * from public.admin_records')).rows.length,0);
 await assert.rejects(()=>db.query("insert into public.admin_users(user_id) values('"+user+"')"));
 await assert.rejects(()=>db.query('select public.admin_report()'));
 await assert.rejects(()=>execute('hash-3',payload));
 await db.exec("set request.jwt.claim.sub='"+admin+"';");
 const report=(await db.query<any>('select public.admin_report() as data')).rows[0].data;
 assert.equal(report.cohort_complete,true);
 const historical=(await db.query<any>("select public.admin_report('{\"from\":\"2000-01-01\"}') as data")).rows[0].data;assert.equal(historical.cohort_complete,false);
 assert.equal(report.total,2);assert.equal(report.starts,3);assert.equal(report.completed,2);assert.equal(report.marketing,1);
 const filtered=(await db.query<any>("select public.admin_report('{\"priority\":\"vision\"}') as data")).rows[0].data;assert.equal(filtered.total,1);assert.equal(filtered.starts,3);
 const injection=(await db.query<any>("select public.admin_report($1::jsonb) as data",[JSON.stringify({search:"' OR 1=1 --"})])).rows[0].data;assert.equal(injection.total,0);
 await assert.rejects(()=>db.query('delete from public.leads'));
 await db.exec("reset role;delete from public.admin_users where user_id='"+admin+"';set role authenticated;");
 assert.equal((await db.query('select * from public.leads')).rows.length,0);
 await assert.rejects(()=>db.query('select public.admin_report()'));
 await db.close();
});
